"""add role to users

Revision ID: 570da29064f6
Revises: 321a2b200d36
Create Date: 2025-12-27 09:53:54.128062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570da29064f6'
down_revision = '321a2b200d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
